# Generated by Django 4.2.7 on 2025-04-12 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('analytics', '0002_remove_learninginsight_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninginsight',
            name='relevance_score',
            field=models.FloatField(default=0.5, help_text='How relevant this insight is to the user (0-1)'),
        ),
        migrations.AlterField(
            model_name='learninginsight',
            name='insight_type',
            field=models.CharField(choices=[('learning_pattern', 'Learning Pattern'), ('engagement', 'Engagement'), ('performance', 'Performance'), ('recommendation', 'Recommendation'), ('study_habit', 'Study Habit'), ('strength', 'Strength'), ('weakness', 'Weakness'), ('learning_style', 'Learning Style'), ('improvement', 'Improvement Area')], max_length=50),
        ),
        migrations.CreateModel(
            name='LearningStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_style', models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading/Writing'), ('kinesthetic', 'Kinesthetic'), ('multimodal', 'Multimodal')], default='multimodal', max_length=20)),
                ('secondary_style', models.CharField(blank=True, choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading/Writing'), ('kinesthetic', 'Kinesthetic'), ('multimodal', 'Multimodal')], max_length=20, null=True)),
                ('pace_preference', models.CharField(choices=[('slow', 'Slow & Thorough'), ('moderate', 'Moderate'), ('fast', 'Fast-Paced'), ('variable', 'Variable')], default='moderate', max_length=20)),
                ('prefers_group_learning', models.BooleanField(default=True)),
                ('prefers_practical_examples', models.BooleanField(default=True)),
                ('prefers_theory_first', models.BooleanField(default=False)),
                ('attention_span_minutes', models.PositiveIntegerField(default=30)),
                ('confidence_level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_style_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Style',
                'verbose_name_plural': 'Learning Styles',
            },
        ),
        migrations.CreateModel(
            name='AILearningRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendation_type', models.CharField(choices=[('course', 'Course Recommendation'), ('resource', 'Learning Resource'), ('study_technique', 'Study Technique'), ('content_format', 'Content Format'), ('practice', 'Practice Exercise'), ('challenge', 'Challenge'), ('learning_path', 'Learning Path')], max_length=30)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(default=0.7, help_text='AI confidence in this recommendation (0-1)')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Learning Recommendation',
                'verbose_name_plural': 'AI Learning Recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
