# Generated by Django 4.2.7 on 2025-04-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_content_difficulty_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='learning_style',
        ),
        migrations.AddField(
            model_name='customuser',
            name='learning_preference',
            field=models.CharField(blank=True, max_length=50, verbose_name='Learning Preference'),
        ),
    ]
