# Generated by Django 4.2.7 on 2025-03-15 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('score', models.FloatField(verbose_name='Score')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Total Questions')),
                ('correct_answers', models.PositiveIntegerField(verbose_name='Correct Answers')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Personalized Quiz Attempt',
                'verbose_name_plural': 'Personalized Quiz Attempts',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Option Text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_set', to='courses.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
    ]
