# Generated by Django 5.2 on 2025-04-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_quizattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Course price (0 for free)', max_digits=10, verbose_name='Price'),
        ),
    ]
