# Generated by Django 4.2.7 on 2025-03-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('quiz_score', 'Quiz Score'), ('course_completion', 'Course Completion'), ('streak', 'Streak'), ('activity', 'Activity')], default='activity', max_length=20),
        ),
    ]
