# Generated by Django 4.2.7 on 2025-03-15 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0002_achievement_achievement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointstransaction',
            options={},
        ),
        migrations.RenameField(
            model_name='pointstransaction',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='userachievement',
            old_name='earned_at',
            new_name='date_earned',
        ),
        migrations.AddField(
            model_name='achievement',
            name='users',
            field=models.ManyToManyField(related_name='achievement_set', through='gamification.UserAchievement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(related_name='badge_set', through='gamification.UserBadge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_earned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point',
                'verbose_name_plural': 'Points',
            },
        ),
    ]
