# Generated by Django 4.2.7 on 2025-04-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_description'),
        ('gamification', '0003_alter_pointstransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('achievement', 'Achievement'), ('progress', 'Progress'), ('activity', 'Activity'), ('special', 'Special'), ('mastery', 'Mastery')], default='achievement', max_length=20),
        ),
        migrations.CreateModel(
            name='ProgressBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_type', models.CharField(choices=[('course_completion', 'Course Completion'), ('module_completion', 'Module Completion'), ('lesson_completion', 'Lesson Completion'), ('quiz_performance', 'Quiz Performance'), ('activity_count', 'Activity Count'), ('points_milestone', 'Points Milestone')], max_length=30)),
                ('threshold', models.PositiveIntegerField(help_text='Target value to achieve for earning the badge')),
                ('min_score', models.PositiveIntegerField(blank=True, help_text='Minimum quiz score required (percentage)', null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('badge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_criteria', to='gamification.badge')),
                ('course', models.ForeignKey(blank=True, help_text='If this badge is specific to a course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('module', models.ForeignKey(blank=True, help_text='If this badge is specific to a module', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.module')),
            ],
        ),
    ]
